### PR TITLE
add easy, hard, déjà_vu flag on level

### PR DESCRIPTION
**Pull request by Bopzor**
[prout](https://framablog.org/2020/11/05/framaprout-ceci-est-une-prout-revolution/)

### CODE REVIEW

**Comment by Bopzor** [comment]
LGTM thanks :fire:

**Comment by nilscox** [comment]
Ok LGTM, let's deploy this
edit: cpac

**Comment by Bopzor** [comment]
@nilscox I need the prod credentials to deploy

**Comment by nilscox** [comment]
> @nilscox I need the prod credentials to deploy

avec plaisir xoxoxo

**Pull request merged**
